### ISSUE TITLE
"Alpha Mask" Sways Independently of Opaque Foliage Texture with Wind Effect

### ISSUE THREAD

**Issue by Professor-CDawg** [zesterer/openmw-shaders#13] opened 2022-06-28 14:32 UTC
I mentioned in #12 that the foliage continued to sway after I set WIND_AMPLITUDE to 0.0. On closer inspection, I realized that at this setting, the opaque part of the foliage textures (the leaves themselves) are actually not swaying; they are stationary as they should be.

However, the "alpha mask" (I'm not sure if this is the correct term or not; I'm referring to the outline around the opaque part of the foliage textures that defines the border where transparency should end/begin) was still swaying, creating a strange visual phenomenon:

https://user-images.githubusercontent.com/68561018/176203813-e0abe00a-909f-430f-810b-feb7a16a3bd4.mp4

 Notice how the "alpha mask" moves around while the actual leaves stay still in space. The "alpha mask" often overlaps the leaves, causing those portions to turn momentarily invisible. Simultaneously, the other end of the mask moves noticeably beyond the edge of the leaves, creating an obvious and animated "hole" in the mist/clouds from the Volumetric Cloud & Mist Mod.

After observing this, I tried setting WIND_AMPLITUDE back to 0.6 to see if the issue was noticeable there as well. I found that it was; while the leaves also move at this value (in addition to the "alpha mask"), they seem to do so independently of the mask, such that the two often visibly move in different directions from one another:

https://user-images.githubusercontent.com/68561018/176205268-cf1c519f-cf7b-4c21-bf8e-61145902cee7.mp4

The effect is rather visually distracting in my opinion.

**Comment by Professor-CDawg** [comment] 2022-06-28 14:33
I posted this in the wrong project (was meant for the Volumetric Cloud & Mist Mod)

**Comment by zesterer** [comment] 2022-06-28 19:47
Interesting! I'll try to get some time to look into this later this week. I think the fix should be relatively trivial...

**Comment by XC3N** [comment] 2022-08-22 15:40
Hello, just jumping in to confirm something, is the effect itself an issue, or this is just in the context of setting WIND_AMPLITUDE to 0.0?

I have the same effect on my side (without modifying anything) which I also find very distracting, is this working as intended?

**Comment by zesterer** [comment] 2022-08-22 16:10
It's not working as intended. Rendering of the leaves happens as two passes: one for the alpha mask during shadow rendering, another to draw the foliage itself. The former doesn't seem to be correctly using the wind effect, so that needs fixing.

**Comment by zesterer** [comment] 2022-08-22 19:09
@Professor-CDawg Out of interest, does this still happen with the latest commit?

**Comment by XC3N** [comment] 2022-08-23 07:09
@zesterer still happening with latest commit but looks different now, before it kinda looked like a "mirror" effect, now it's got two separate shadows moving about
![bug](https://user-images.githubusercontent.com/31542509/186093698-d4d25b30-0523-4075-9d36-3c2cce42f831.png)
.

**Comment by zesterer** [comment] 2022-08-23 10:49
Could you give an overview of the shader settings you have?

**Comment by XC3N** [comment] 2022-08-23 11:18
if you are referring to the config.glsl file, it's the one from the latest commit. Only change is to set preset to VANILLA.

**Comment by zesterer** [comment] 2022-08-23 11:39
I mean your game settings. Alpha to coverage, etc. You should find it in your `settings.cfg` file.

**Comment by XC3N** [comment] 2022-08-23 13:26
The only things I modified are thing you suggested ;) I will link the file.

FYI, I just installed the Morrowind Optimization Patch: it makes the issue go away
[settings.cfg.txt](https://github.com/zesterer/openmw-shaders/files/9402871/settings.cfg.txt)
.

**Comment by zesterer** [comment] 2022-08-23 13:44
Ah, that's definitely interesting to note. I do most of my testing with the optimisation patch. Hopefully this is enough for me to investigate further, thanks for the details!

**Comment by zesterer** [comment] 2022-08-23 18:25
@XC3N Out of interest, do I see what you have my cloud mod enabled too? Do you still observe this effect if it's disabled?

**Comment by XC3N** [comment] 2022-08-24 07:43
Just performed some tests, disabled both MOP and your Cloud mod: problem is *not* present.
Re-enabled cloud mod without MOP: problem *is* present
Re-enabled MOP on top of cloud mod: Problem is *not* present

let me know if I can perform more tests for you

**Comment by zesterer** [comment] 2022-08-25 18:15
@XC3N Could you confirm whether this issue was fixed in the latest commit?

**Comment by XC3N** [comment] 2022-08-29 10:31
hey @zesterer, just got time to check and the issue is fixed! Good work!

**Closed** 2022-08-29 11:01 UTC
