### ISSUE TITLE
Extremely dark shadows in interiors

### ISSUE THREAD

**Issue by DieuDeGlace** [zesterer/openmw-shaders#26] opened 2022-10-18 05:50 UTC
The title says it all really. I am seeings that in a lot of the interiors around seyda neen (and other buildings i have been to) have this weird shadow effect going on where it over darkens spots while leaving the rest of it untouched. increasing interior brightness does nothing against it and i know its the shaders as when i go back to the default openmw ones it doesn't exist. I love these shaders simply because of the water caustics and underwater stuff; however, interiors are buggy as all hell for me. I have installed the shaders to a custom resources folder and have the game directed to that. clamp lighting is off and force per pixel lighting is needed to be on otherwise the shaders dont work. 

below is an image showing exactly what im talking about. As you can see the npc off to the right is borderline impossible to see. this effect happens in some corners of homes/buildings and some dwemer ruins are borderline hard to see around.

![openmw 2022-10-18 00-43-32](https://user-images.githubusercontent.com/47928395/196346169-a5248273-c1bc-4b70-bd13-996360dfd2f1.png)

**Comment by zesterer** [comment] 2022-11-21 20:54
Do you have any errors in the console/logs when running the game?

**Comment by jtuu** [comment] 2022-11-28 04:26
I ran into the same problem. Game looks normal with stock shaders but with these shaders some interiors are dark. Dark interiors include Vivec mages guild and Aldruhn mages guild. Balmora mages guild is not dark. I'm using OpenMW master a00382d6.

Log of starting a new game and teleporting into Vivec mages guild. No mods enabled.
[openmw.log](https://github.com/zesterer/openmw-shaders/files/10100405/openmw.log)

Sometimes there would be a warning like this, but not every time:
Warning: detected OpenGL error 'invalid operation' at after RenderBin::draw(..)

**Comment by jtuu** [comment] 2022-11-28 15:25
https://github.com/zesterer/openmw-shaders/blob/69097f8c43207812ad639cf29ce7eadbee62a46c/shaders/pbr.glsl#L168-L169

Pretty sure this line is the culprit. Changing it to 1.0 fixes the dark interiors, but then everything else looks wrong of course.

**Comment by zesterer** [comment] 2022-11-30 15:23
Hmm. It would be nice to have a better way to determine this in the shaders. Perhaps I should request this from the OpenMW team.

**Comment by zesterer** [comment] 2022-12-01 14:52
So the issue is that OpenMW doesn't currently pass any information to the shaders saying "We're indoors right now". Knowing when we're indoors is important, because it changes how "sunlight" (the original Morrowind had a very cursed form of sunlight indoors too) gets applied to the scene.

As a result, this line tries to guess whether we're indoors based on the angle of the sun and also how bright it is, because 90% of indoor scenes in Morrowind have a very specific setup for the sun.

Except, some break this trend. Like the Mage's Guild in Vivec. For some reason, its sunlight is slightly different: different enough that this line breaks.

The 'proper' solution would be to get OpenMW to just tell the shaders when we're indoors. I did this to solve a similar-ish issue for reflections in [this MR](https://gitlab.com/OpenMW/openmw/-/merge_requests/2340). I'm probably not going to have the time to look into this for about a week though, sadly.

**Comment by jtuu** [comment] 2022-12-12 23:19
Looks like this might be fixed now?

**Comment by zesterer** [comment] 2022-12-12 23:22
It should be, yes. Happy to re-open if anybody else hits this issue again.

**Closed by zesterer** 2022-12-12 23:22 UTC

**Comment by DieuDeGlace** [comment] 2023-01-05 08:56
could be doing something wrong, but it seems the issue still remains on my end? dont know if jtuu can also confirm it, but the same spots i pointed out are still suffering from the original issue.

**Comment by zesterer** [comment] 2023-01-05 11:38
Are you using the latest release? And do you have the names of the exact locations?

**Comment by DieuDeGlace** [comment] 2023-01-06 03:53
Yeah I'm on the latest openmw, using the latest shaders. I apologize for being so picky about this lol, but its noticed at the start of the game when you are in the office (at least for me), and the lighthouse. (both are in seyda neen so again this is me being nitpicky but I fear that its existence here means it will be the same in other places). Ill provide pictures below.

![openmw 2023-01-05 21-45-58](https://user-images.githubusercontent.com/47928395/210926694-d5332b47-438b-4570-bfd6-8f53c3e62714.png)


![openmw 2023-01-05 21-45-38](https://user-images.githubusercontent.com/47928395/210926609-6e53847c-0367-447e-90ed-85a38bd69184.png)

**Comment by DieuDeGlace** [comment] 2023-01-06 03:54
i will check other spots previously mentioned to make sure.

**Comment by DieuDeGlace** [comment] 2023-01-06 03:55
[openmw.log](https://github.com/zesterer/openmw-shaders/files/10357203/openmw.log)
here is the log file

**Comment by DieuDeGlace** [comment] 2023-01-06 03:59
seems previously mentioned places are fine so its just these spots from what ive gathered. dont know if its cell dependent or something.

**Comment by NaturalHalfling** [comment] 2024-02-21 16:15
I'm also getting this issue, in that office in seyda neen near the fire and also in the lighthouse, and that house in ald ruhn with the corpus in it, it's compeltely pitch black downstairs. Removing the shader has not fixed it nor has changing lighting methods (shader/compatibility/legacy) done anything but I am sure it must be something to do with it because it was not there before installing the shader.
